# Generated by Django 4.0.3 on 2023-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('oname', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='flipcart_app/static')),
            ],
        ),
    ]
