# Generated by Django 4.0.3 on 2023-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregmodel',
            name='pic',
            field=models.FileField(upload_to='flipcart_app/static'),
        ),
    ]
