# Generated by Django 4.1.4 on 2023-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart_app', '0002_alter_shopregmodel_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopaddmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=30)),
                ('iprice', models.IntegerField()),
                ('idisc', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('iimage', models.FileField(upload_to='flipcart_app/static')),
            ],
        ),
    ]
