# Generated by Django 4.0.3 on 2023-02-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart_app', '0005_userregmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregmodel',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
